language: ruby
sudo: false
cache: bundler

services: redis

before_install: gem install bundler

script: bundle exec rake
before_script:
  - cd test/dummy && RAILS_ENV=test bundle exec rake db:migrate && cd -

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head

gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
